### ISSUE TITLE
Schematic

### ISSUE THREAD

**Issue by yaani** [DeanIsMe/SevSeg#1]
Pls provide the schematic and also the way it can be used to show negative value.
thanks

**Comment by Zblay** [comment]
http://fritzing.org/projects/test-4-digits-7-segments-displays

This worked for me

**Comment by houguang** [comment]
sevseg.setBrightness(0);没有效果,不管值是多少,亮度没有变化.

**Comment by Bowserw2c** [comment]
sevseg.setBrightness(0); doesn't work for me as well.
Please also tell how to display several numbers one after another.

**Comment by jrlvrghs** [comment]
How to control the brightness without PWM pins?

**Comment by DeanIsMe** [comment]
All LED output lines are continuously being turned on and off as refreshDisplay() is called. When the brightness is set higher, the LEDs stay on for a little longer.

**Comment by frycu102** [comment]
Regardless the settings "sevseg.setBrightness(0)" the brightness has not being changed. Some advice, please.

**Comment by jrlvrghs** [comment]
I think you have to use the PWM pins to adjust the brightness. Please refer
to the arduino brightness control example.

**Comment by frycu102** [comment]
Pins "Digit Pins" have connected to PWM. 
It's not helping.

**Comment by jrlvrghs** [comment]
Are you using that analogWrite(); to give the outputs?

**Comment by DeanIsMe** [comment]
AnalogWrite is not used. Delays are used. This is way off track, so I'm closing it.
