### ISSUE TITLE
Turn Off digit

### ISSUE THREAD

**Issue by Vitor1827** [DeanIsMe/SevSeg#100]
Hi,
there's no way to turn a single digit Off an On? I want to make the effect like you'r selecting a digit. Trie'd the digitOff() function, but no success at all...

**Comment by DeanIsMe** [comment]
Hi,
The easiest way to turn a specific digit off is with the `setSegmentsDigit` function.
After you set the display with `setNumber` or `setChars`, call `setSegmentsDigit` with segs=0 to blank a particular digit.
