### ISSUE TITLE
testWholeDisplay example

### ISSUE THREAD

**Issue by KwisScram** [DeanIsMe/SevSeg#105]
I hope I write this in the right place. Sorry in advance if I am doing wrong. I'am pretty new to GitHub.

In the example sketch "testWholeDisplay " there is a dead link.
https://www.arduino.cc/en/Reference/Modulo

Maybe it should be
https://www.arduino.cc/reference/en/language/structure/arithmetic-operators/remainder

**Comment by DeanIsMe** [comment]
Thanks for letting me know! I plan on replacing the entire testWholeDisplay sketch, so I'll leave this issue up to push me to do that.

**Comment by DeanIsMe** [comment]
I just pushed an entirely new testDisplay sketch!
