### ISSUE TITLE
Refresh delay

### ISSUE THREAD

**Issue by czcoxx** [DeanIsMe/SevSeg#12]
Hello,
I am beginner... I would like to ask how can I put delay to code. I want to display temperature from sensor every 1 minute, but if I use Delay command in code the LED display doesn't work.

Thank you for advice

**Comment by DeanIsMe** [comment]
Hi,


Open up

File->Examples->Basics->Blink

and File->Examples->Digital->BlinkWithoutDelay


Blink uses Delay() and BlinkWithoutDelay() achieves the same thing using a timer variable (currentMillis) and the millis() function.



So pretty much, all that you need to do in your main loop:


unsigned long sensorTimer = 0;

if (millis() - sensorTimer > 60000) {

sensorTimer = millis();

// Do the measurement

...

}


Good luck,

Dean

________________________________
