### ISSUE TITLE
Allow compiles with -Werror

### ISSUE THREAD

**Issue by leres** [DeanIsMe/SevSeg#16]
I try to always work with -Wall -Werror, etc. and that is not compatible with turning on RESISTORS_ON_SEGMENTS:
```
avr-g++ -mmcu=atmega328p -g -Os -fno-exceptions -ffunction-sections -fdata-sections -DF_CPU=16000000L -DARDUINO=106 -Wall -Werror -DRESISTORS_ON_SEGMENTS=1 -I. -I/usr/local/arduino/hardware/arduino/cores/arduino -I/usr/local/arduino/hardware/arduino/variants/standard -I/usr/local/arduino/libraries/SevSeg -c test.cpp -o test.o
In file included from test.cpp:21:0:
/usr/local/arduino/libraries/SevSeg/SevSeg.h:26:0: error: "RESISTORS_ON_SEGMENTS" redefined [-Werror]
 #define RESISTORS_ON_SEGMENTS 0
  ^
<command-line>:0:0: note: this is the location of the previous definition
cc1plus: all warnings being treated as errors
*** Error code 1

Stop.
```
Here's a patch to SevSeg.h that keeps only defines RESISTORS_ON_SEGMENTS and MAXNUMDIGITS when they are not already defined: [patch-SevSeg.h](https://gist.github.com/leres/885ba971ecde892338b93d5fba927b7b
)

**Comment by DeanIsMe** [comment]
I should have done this when I originally wrote it. However, the latest release of the SevSeg library no longer uses #define RESISTORS_ON_SEGMENTS, so that will no longer generate a warning.
