### ISSUE TITLE
Improve with degree °

### ISSUE THREAD

**Issue by alexrtou** [DeanIsMe/SevSeg#19]
Hello,
good Job. It's works realy fine ! just a simple suggestion: can you add degree char ? that's use full for temperatures :)

probably : 

```
static const byte digitCodeMap[] = {
//     GFEDCBA  Segments      7-segment map:
...
     B01100011, // ??  '°'  DEGREE
};
```

**Comment by DeanIsMe** [comment]
Hi Alex,


Considering that it can't be easily typed and it doesn't draw well on a seven segment display, I don't think I'll include it in the core library.

It seems that you've already figured out how to add it to your own library though.


-Dean

________________________________

**Comment by alexrtou** [comment]
no problem ! it was just an idea.
