### ISSUE TITLE
Brightness control doesn't work

### ISSUE THREAD

**Issue by Bowserw2c** [DeanIsMe/SevSeg#20]
sevseg.setBrightness(10); doesn't change brightness.

**Comment by DeanIsMe** [comment]
Among other things, the actual brightness that you see will depend on:

- the characteristics of your display
- the size of your display
- your circuit to drive it
- the clock speed of your arduino
- the other functions running in your loop
- the configuration of the library (most importantly, updateWithDelays)

It's possible that you may not see a brightness difference between 100 and 10.
