### ISSUE TITLE
Cannot display "." 

### ISSUE THREAD

**Issue by Bowserw2c** [DeanIsMe/SevSeg#21]
you have taken the input from pin 13 to dp pin of 7 segment display but there is no control in your code to turn the decimal point on.

**Comment by DeanIsMe** [comment]
The decimal point will turn on when displaying a number, via the setNumber command. If I supported the decimal point via setChars command, it would take up an entire character (resulting in less space, and bad number rendering).
Example:
`setChars("3.14");      Will display [3 .14]` (Bad rendering)
Whereas
`setNumber(314, 2); Will display [ 3.14]` (Looks good)
That is why I chose not to include the decimal place in setChars().

**Comment by Bowserw2c** [comment]
Ok thanks for the explanation ... and thanks for the library!
