### ISSUE TITLE
Single Digits Are No Fun

### ISSUE THREAD

**Issue by Markus-Hammer** [DeanIsMe/SevSeg#26]
I can see how the configuration works for multiple digit displays, but what about a single digit display like the 5101AS? Dose the library support this, or am i just missing something?

**Comment by DeanIsMe** [comment]
I'm not aware of any reason why this library wouldn't work with a single digit display. Have you tried it? Where are you getting stuck?
From a brief look, it seems like the 5101AS is COMMON CATHODE type display.
