### ISSUE TITLE
sevseg.refreshDisplay - Invalid use of non-static member function

### ISSUE THREAD

**Issue by jsgarden** [DeanIsMe/SevSeg#27]
Whenever I use that command in setup or loop and I try to compile, the IDE gives me that error: Invalid use of non-static member function

**Comment by DeanIsMe** [comment]
You need to define a sevseg object and call refreshDisplay on that object. I suspect you may not be doing that.
If you show me your script I can tell you what's wrong.

________________________________

**Comment by jsgarden** [comment]
Everything works now, thanks ! I wasn't declaring a sevseg object properly.
