### ISSUE TITLE
how do i increase the delay in the countdown function

### ISSUE THREAD

**Issue by ClumsyPenguin** [DeanIsMe/SevSeg#30]
i have tried multiple things and played with the code
i can only speed up the countdown not slow it down

**Comment by DeanIsMe** [comment]
I think that you should follow some introductory tutorials on C++ for Arduino. Make sure you understand the example BlinkWithoutDelay

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________
