### ISSUE TITLE
delay

### ISSUE THREAD

**Issue by makabaka123456** [DeanIsMe/SevSeg#32]
can you tell me how to make my code true?
void loop() {
  for(int i=-9;i<=-1;i++)
  sevseg.setNumber(i);
  delay(1000);
  sevseg.refreshDisplay();// Must run repeatedly
}
i don't konw why it's wrong
thank you so much

**Comment by dzanis** [comment]
dont use delay 
Look alternative delay example
```
unsigned long prevUpdate = 0; 
int i = -9;

void loop() {

unsigned long currentUpdate = millis();

 if(currentUpdate - prevUpdate >= 1000) {
    prevUpdate = currentUpdate;  
if( i <= -1)
  i++;
sevseg.setNumber(i);
  }

//delay(1000); 

sevseg.refreshDisplay();// Must run repeatedly
}
```
