### ISSUE TITLE
4 Digit 7 Segment display upper led always on

### ISSUE THREAD

**Issue by ItsVince1234** [DeanIsMe/SevSeg#37]
Like the title says, here is my code:
I mean this (+ is on - is off):
  +   +   +   +           +   +   +   +          +   +   +   +          +   +   +   + 
-    -    -    -    -     -    -    -    -    -      -    -    -    -    -      -    -    -    -    -
  -    -     -    -           -    -     -    -         -    -     -    -            -    -     -    -
-    -    -    -    -      -    -    -    -    -      -    -    -    -    -      -    -    -    -    -
-    -     -    -             -    -     -    -           -    -     -    -           -    -     -    -

// Arduino Light sensor code created by AR Builder.
#include "SevSeg.h"
SevSeg sevseg; 
void setup() {
 int A = analogRead(A0);
  Serial.begin(9600); // Start Serial.
  pinMode(13, OUTPUT);
  byte numDigits = 4;
  byte digitPins[] = {9, 10, 11, 12};
  byte segmentPins[] = {1, 2, 3, 4, 5, 6, 7, 8};

  bool resistorsOnSegments = false; 
  bool updateWithDelaysIn = true;
  byte hardwareConfig = COMMON_CATHODE; 
  sevseg.begin(hardwareConfig, numDigits, digitPins, segmentPins, resistorsOnSegments);
  sevseg.setBrightness(90);
}
  

void loop() {
 sevseg.blank();
int A = analogRead(A0);
{
   if (A < 150) {
     sevseg.setNumber(150,3);
    sevseg.refreshDisplay(); 
   }
   else{
     sevseg.blank();
   }
}
}

**Comment by DeanIsMe** [comment]
Hi,

It's most likely that you don't have the right pins connected for your particular display. Confirm that each segment and digit pin is correct.

-Dean
________________________________

**Comment by emilianos** [comment]
Hi,
I'm experiencing the same issue:
Only the top segment of the first digit is always on.
I checked several times and it's properly connected.. also I think if it was a problem with that segment A, it should fail for every digit not just first one..

![gif-2018-07-13-11-50-51](https://user-images.githubusercontent.com/4334689/42698032-23cf1346-8693-11e8-9e82-4d044caad506.gif)

**Comment by emilianos** [comment]
Hi I was having the same issue, and I found out that it happens when CP is not assigned a PIN:
```
byte segmentPins[] = {2, 3, 4, 5, 6, 7, 8, 13}; //Segments: A,B,C,D,E,F,G,CP
```
to avoid the issue assign any pin to CP (13 in this case), otherwise it will show a segment on on the first digit

**Comment by DeanIsMe** [comment]
Hi @emilianos, note that @ItsVince1234  has pin numbers for all 8 segments defined

**Comment by DeanIsMe** [comment]
I realised the problem tonight - it occurred because sevseg.refreshDisplay(); was no longer being called. I just make a commit that should improve the blank() functionality.
0116b56
