### ISSUE TITLE
Incompatible with Analog Pins on Arduino Nano

### ISSUE THREAD

**Issue by nsd4fr** [DeanIsMe/SevSeg#38]
Hi DeanIsMe!

I just wanted to report a small issue with the [Arduino Nano](https://store.arduino.cc/usa/arduino-nano) with this code. Unlike other Arduino architectures such as the Uno, certain analog pins CANNOT be used as digital pins. Specifically on the Nano, A6 and A7. I wired up a quick little circuit with the display and confirmed that this is true. 

I would recommend revising the statement on the main page. 

> All digit pins and segment pins can be connected to any of the Arduino's digital or analog pins; just make sure you take note of your connections!

Consider adding the disclaimer

> ...any of the Arduino's digital or analog pins (with digital support)...

Thanks for reading!

**Comment by DeanIsMe** [comment]
Hi,
Thanks for the heads up! I wasn't aware of this exception.
I'll change it when my holidays end.

Cheers,
Dean
________________________________
