### ISSUE TITLE
Dual display

### ISSUE THREAD

**Issue by marabesi** [DeanIsMe/SevSeg#40]
I have a dual 7segment display which I'd like to display decimal numbers using the SevSeg lib.

However I couldn't find the pins I should use. I did a few tests and I could power on only one side of the digits.

Here is the display I am using 
<img width="324" alt="captura de pantalla 2018-08-13 a la s 12 24 44" src="https://user-images.githubusercontent.com/2129872/44041329-e8fcb808-9ef3-11e8-8dbf-855aecf74c00.png">

Is there a correct map to use ?

Thank you

**Comment by DeanIsMe** [comment]
Hi,
From the picture that you sent, I recommend to connect A1 to A2, B1 to B2, etc. These 8 nodes you'll need to also connect to the arduino and configure as segment pins. Common1 and common2 should your digit pins, so connect these to the arduino.

Regards,
Dean
________________________________
