### ISSUE TITLE
Numbers not displaying correctly 

### ISSUE THREAD

**Issue by EC-ENG** [DeanIsMe/SevSeg#52]
I'm having an issue where  sevseg.setNumber(0050,0); Is being displayed as 40 and 
sevseg.setNumber(0040,0); is being displayed as 32.  This is also happening with various other numbers however majority of numbers display correctly.  I have tested the circuit using the counter and test example and it works correctly.

**Comment by DeanIsMe** [comment]
Hi, your problem has a very simple solution: when your number (literal) starts with a '0', that means 'octal format'. https://www.arduino.cc/reference/en/language/variables/constants/integerconstants/
So, 0050 = 050 = 40 and 0040 = 040 = 32.
https://www.arduino.cc/reference/en/language/variables/constants/integerconstants/
