### ISSUE TITLE
Use without decimal point segment?

### ISSUE THREAD

**Issue by RossAWaddell** [DeanIsMe/SevSeg#57]
I'm using a common anode, single digit display but I only need the 7 segments, not the decimal point. Can I leave that 8th pin out? This is what I have currently, but I really need to not use that 8th pin:

```
  // 7-segment LED display setup
  byte numDigits = 1;
  byte digitPins[] = {};
  byte segmentPins[] = {4, 7, 8, 17, 18, 19, 20, 21};
  bool resistorsOnSegments = true;
  byte hardwareConfig = COMMON_ANODE; 
  sevseg.begin(hardwareConfig, numDigits, digitPins, segmentPins, resistorsOnSegments);
  sevseg.setBrightness(10); 
```

**Comment by DeanIsMe** [comment]
Hi Ross,
Please read the Software 'setting up' section in the readme. You can disable the decimal point.
