### ISSUE TITLE
Suggested code wrapper for displaying on 7 seg.

### ISSUE THREAD

**Issue by S-Ramdath** [DeanIsMe/SevSeg#58]
/* Just some code i threw together to make things easier for me. Has some errors. I think this would make things easier for the coders out there.
*/
void show(float a, int decimalPlaces, int time_value, SevSeg entity) {
  entity.setNumber(a, decimalPlaces);
  entity.refreshDisplay();
  delay(time_value);
}

void show(const char str, int wordLength, int time_value, SevSeg entity) {
  //char str2[str.length()]; //take in string into charr array
  char str2[wordLength]; //take in string into charr array
  float i;
  //for (i = 0 ; i < str.length(); i++) {
  for (i = 0 ; i < wordLength; i++) {
    str2[i] = str[i];
  }
  entity.setChars(str2);//pass char array to func nw
  entity.refreshDisplay();
  delay(time_value);
}

**Comment by DeanIsMe** [comment]
This is not how the SevSeg library should be used. Refer to the SevSeg documentation and SevSeg examples.
