### ISSUE TITLE
Problem With Digital Pin 0

### ISSUE THREAD

**Issue by matthewfelgate2** [DeanIsMe/SevSeg#66]
I have wired one of the segments of my 4-digit 7-segment display to digital pin 0. Which I think is a valid digital pin on the Arduino chip. However byte `segmentPins[]` doesn't seem to allow a `0` in the array. Am I doing something wrong or is the software not able to handle that as one of the pin numbers? 

PS Thanks for the great software!

**Comment by bridystone** [comment]
Hi @matthewfelgate2,

This shouldn't result in any issues.
The library only forwards the port number.

What actually is the problem?

I actually had a problem with PIN 0 as well, when I activated Debugging with the Serial Monitor on my Uno 3. The Serial Monitor uses PIN 0 (RX) to push the serial data via USB to the computer.
(Reason is that PINs 0 and 1 are used for the USB communication)

Would your problem solve, when you would not use the Serial Class in your code?
If not, it would be helpful to have some code to look at and a description which board you use.

Jens
