### ISSUE TITLE
The speed I should use is 115200

### ISSUE THREAD

**Issue by zk317** [DeanIsMe/SevSeg#67]
Hi guys
Thank you for using it so well
But there is a problem.
The speed I should use is 115200
This only supports 9600
How can there be no way?
It's an Arduino Uno board so there's no other choice
Thanks for reading

**Comment by DeanIsMe** [comment]
Hi,

I think that you have a lot to learn about the Arduino world, before you start using the SevSeg library.

Here is one location with some tutorials.
https://www.arduino.cc/en/Tutorial/HomePage?from=Main.Tutorials

Also, see here:
https://www.arduino.cc/reference/en/language/functions/communication/serial/begin/
Regards,

Dean
