### ISSUE TITLE
leading zeros?

### ISSUE THREAD

**Issue by L8zin** [DeanIsMe/SevSeg#68]
Hello, I might've caught the stupid virus here but I can't figure out how to get leading zeros working. I have a float as the output with 1 decimal place:

`  sevseg.setNumber(average,1);`

This is my setup:

`byte numDigits = 4;
byte digitPins[] = {13, 12, 11, 10};
byte segmentPins[] = {2, 3, 4, 5, 6, 7, 8, 9};
bool leadingZeros = true;
sevseg.begin(COMMON_CATHODE, numDigits, digitPins, segmentPins, leadingZeros); `

**Comment by L8zin** [comment]
I am very new to this and I created this account just to post this

**Comment by L8zin** [comment]
I seem to have fixed my own problem by changing `if (!leadingzeros)` to `if (leading zeros = false)` in the SevSeg.cpp. You might want to look into this though.

**Comment by DeanIsMe** [comment]
Hmmm `leadingZeros` is `bool`, so `!leadingZeros` should be equivalent to `leadingZeros == false`.
If anyone else is having an issue, please post here.

**Comment by machmar** [comment]
I just wanna comment that `if (leading zeros = false)` means that it will always skip the if loop.

**Comment by DeanIsMe** [comment]
Yes, and the loop removes the leading zeros. Hence, in the case of L8zin the leading zeros will remain and be displayed. 
Given the lack of activity, I will close this issue.
