### ISSUE TITLE
Please issue a release

### ISSUE THREAD

**Issue by leres** [DeanIsMe/SevSeg#7]
Could you please issue a release with a version number? I have a FreeBSD port I'd like to submit and although it's possible to download the current version using the tag name ba10676f8505b5ceb47d32f6ef3222ef2067c4cd, having an actual release version number would be much cleaner.

Thanks!

**Comment by DeanIsMe** [comment]
Release issued with version number 3.1.

**Comment by leres** [comment]
Thanks for the quick response. However it looks like you put a version 3.1 comment in one of the source files. What I was hoping for was a github release called 3.1. That way the FreeBSD port can download a package that contains all of the files as of the release date.

**Comment by DeanIsMe** [comment]
Ah I see. I wasn't aware of the 'Release' option on Github. I believe that I have now made v3.1 the first 'Release'.

**Comment by leres** [comment]
On 09/17/16 18:01, Dean Reading wrote:
> Ah I see. I wasn't aware of the 'Release' option on Github. I believe
> that I have now made v3.1 the first 'Release'.

FYI, this is finally available as a FreeBSD port:

    https://www.freshports.org/devel/arduino-sevseg/

		Craig
