### ISSUE TITLE
Display of numbers

### ISSUE THREAD

**Issue by Noctis-E** [DeanIsMe/SevSeg#72]
Hi! I noticed a small issue with the display of numbers 0, 2 and 3.
I had to modify the initial code changing lines 60, 62 and 63 of cpp's file.

`
B01011111, // 0
B00111011, // 2
B00101111, // 3
`

**Comment by DeanIsMe** [comment]
Hi Noctis,
It looks like you have the wiring mixed up for segments 'F' and 'G. I recommend modifying 'segmentPinsIn' to correct this.
