### ISSUE TITLE
Won't Compile on Arduino IDE

### ISSUE THREAD

**Issue by brendanstennett** [DeanIsMe/SevSeg#75]
I am receiving an error trying to compile the the header does not match the implementation.

Using Arduino 2:1.0.5

In SevSeg.h:
https://github.com/DeanIsMe/SevSeg/blob/master/SevSeg.h#L68

In SevSeg.cpp
https://github.com/DeanIsMe/SevSeg/blob/master/SevSeg.cpp#L473

The addition of the `const` is causing a compile error.  Removing this fixed the issue.

**Comment by DeanIsMe** [comment]
Thanks for bringing this up. I need to pay more attention before merging pull requests. Issues fixed by 6f21f068651c633d0e94df0d580cf43a137b59ce.

**Comment by brendanstennett** [comment]
Yeah no problem, thanks for the great library!
