### ISSUE TITLE
  byte hardwareConfig = NP_COMMMON_CATHODE;  doesn't work

### ISSUE THREAD

**Issue by schroepfer** [DeanIsMe/SevSeg#77]
Hello,
i have big Displays that uses N-type AND P-type transistors with common cathode.

Your example with
  byte hardwareConfig = NP_COMMMON_CATHODE;

gives an Error:
D:\sketchbook\7-Segment-Anzeige\7-Segment-Anzeige.ino: In function 'void setup()':
7-Segment-Anzeige:29:25: error: 'NP_COMMMON_CATHODE' was not declared in this scope
   byte hardwareConfig = NP_COMMMON_CATHODE; // See README.md for options
                         ^
exit status 1
'NP_COMMMON_CATHODE' was not declared in this scope

Please could you help?
Regards
Juergen

**Comment by DeanIsMe** [comment]
Hallo Juergen,
Du hast ein Rechtschreibfehler gemacht. Anderst du 'NP_COMMMON_CATHODE' in 'NP_COMMON_CATHODE'.
-Dean
