### ISSUE TITLE
warning: 'B00111111' is deprecated

### ISSUE THREAD

**Issue by cwilling** [DeanIsMe/SevSeg#84]
I've just started playing with the library on a Nano 33 IoT board & Arduino IDE  1.8.13. Simply including SevSeg.h gives a number of compile time warnings like:

> /home/chris/Arduino/libraries/SevSeg-3.6.1/SevSeg.cpp:48:3:_ warning: 'B00111111' is deprecated: use 0b00111111 instead

I replaced all the B's with 0b as suggested and the warnings have now ceased. Not sure if this warrants a PR?

**Comment by DeanIsMe** [comment]
Thanks for letting me know. I removed all of the 'B...' literals from the library. See commit 
870b43224fe696fd401dbd48f9f50436829825e0
